site_name: Blender Developer Documentation
repo_url: https://github.com/julianeisel/devdocs
edit_uri: edit/main/docs

theme:
  name: material
  icon:
    # Blender logos comes with material icons :)
    logo: material/blender-software
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.action.view
    - content.action.edit
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: deep orange
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: teal
      primary: teal
      toggle:
        icon: material/brightness-3
        name: Switch to light mode


nav:
  - 'Home': 'index.md'
  - 'Developer Handbook':
    - 'developer_handbook/index.md'
    - 'New Developer Introduction':
      - 'developer_handbook/new_developer_introduction/index.md'
      - 'Advice': 'developer_handbook/new_developer_introduction/advice.md'
      - 'Choosing a First Task': 'developer_handbook/new_developer_introduction/choosing_a_first_task.md'
    - 'Building Blender':
      - 'developer_handbook/building_blender/index.md'
      - 'Linux': 'developer_handbook/building_blender/linux.md'
      - 'Windows': 'developer_handbook/building_blender/windows.md'
      - 'macOS': 'developer_handbook/building_blender/macOS.md'
    - 'Process':
      - 'developer_handbook/process/index.md'
      - 'Release Cycle': 'developer_handbook/process/release_cycle.md'
      - 'Contributing (Review & Commit)': 'developer_handbook/process/contributing.md'
    - 'Modules': 'developer_handbook/modules.md'
    - 'Guidelines':
      - 'developer_handbook/guidelines/index.md'
      - 'C/C++ Code Style': 'developer_handbook/guidelines/c_cpp_code_style.md'
      - 'Python Code Style': 'developer_handbook/guidelines/python_code_style.md'
      - 'Commit Messages': 'developer_handbook/guidelines/commit_messages.md'
      - 'Release Notes': 'developer_handbook/guidelines/commit_messages.md'
    - 'Testing':
      - 'developer_handbook/testing/index.md'
      - 'C/C++': 'developer_handbook/testing/c_cpp_tests.md'
      - 'Python': 'developer_handbook/testing/python_tests.md'
    - 'Tools':
      - 'developer_handbook/tools/index.md'
      - 'Address Sanitizer': 'developer_handbook/tools/address_sanitizer.md'
  - 'Core Data Management':
    - 'core_data_management/index.md'
    - 'Datablocks and Main Database':
      - 'core_data_management/datablocks_and_main_database/index.md'
      - 'core_data_management/datablocks_and_main_database/dummy_page.md'
    - 'Blend-File Read/Write':
      - 'core_data_management/blend_file_read_write/index.md'
      - 'core_data_management/blend_file_read_write/dummy_page.md'
    - 'Undo/Redo':
      - 'core_data_management/undo_redo/index.md'
      - 'core_data_management/undo_redo/dummy_page.md'
    - 'DNA':
      - 'core_data_management/dna/index.md'
    - 'RNA':
      - 'core_data_management/rna/index.md'
  - 'Asset System':
    - 'Introduction': 'asset_system/index.md'
    - 'Fundamentals':
      - 'Important Concepts': 'asset_system/fundamentals/index.md'
      - 'asset_system/fundamentals/architectural_overview.md'
      - 'asset_system/fundamentals/from_file_browser_to_asset_system.md'
    - 'Backend':
      - 'asset_system/backend/index.md'
      - 'asset_system/backend/asset_catalogs.md'
      - 'asset_system/backend/asset_list_api.md'
      - 'asset_system/backend/asset_index.md'
    - 'User Interface':
      - 'asset_system/user_interface/index.md'
      - 'asset_system/user_interface/asset_browser.md'
      - 'asset_system/user_interface/asset_shelf.md'
    - ' ':
      - 'FAQ': 'asset_system/FAQ.md'
  # Some dummy categories to show/test main navigation:
  - 'Animation':
    - 'animation/index.md'
  - 'User Interface':
    - 'user_interface_core/index.md'
    - 'Window Manager'
  - 'Rendering':
    - 'rendering/index.md'
  # - 'Nodes & Physics':
  #   - 'nodes_and_physics/index.md'
  # - 'Eevee & Viewport':
  #   - 'eevee_and_viewport/index.md'
  # - 'Sculpt & Paint':
  #   - 'sculpt_and_paint/index.md'
  # - 'Modeling':
  #   - 'modeling/index.md'
  # - 'Platforms, Builds, Tests & Devices':
  #   - 'platforms_builds_tests_and_devices/index.md'
  - 'contributing.md'

markdown_extensions:
  - toc:
      permalink: True
  - callouts
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - section-index
  - glightbox
  - search
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true

extra_css:
  - stylesheets/extra.css